### PR TITLE
Implement login page

### LINKED ISSUE #1: [Feature] Create login screen
### Description

Create the login screen. No need for registration because all users must be pre-identified from Helix as judges

### Designs

_No response_

### PR DESCRIPTION
**Pull request by hdavidethan**
# Description

Closes #1 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by gramliu** [comment]
image

There is a weird bug on deploy previews

**Comment by hdavidethan** [comment]
Oops there's supposed to be a secret env value

**Comment by gramliu** [comment]
Sign out button looks a bit weird on mobile
image

**Comment by gramliu** [comment]
Login header also looks weird on mobile but that's my fault
image

**Review by gramliu — APPROVED** [review]

**Pull request merged**
